### PR TITLE
Flatten the CoC in a single document page

### LINKED ISSUE #13: Three-document format or one-document?
When I shared around the JSFoundation code of conduct before the January meeting, a few people responded with the general message, "where's the specificity around reporting and enforcement"? It's there, just in two separate, linked documents. This code of conduct preserves the factoring. I see a big benefit in terms of, most of the time, people should just think about the recommendations for their own conduct. However, is this format sufficient for the committee to do reviews? Should it be in a single document for ease of skimming, as most other CoCs are?

### PR DESCRIPTION
**Pull request by leobalter**
Fixes #13

### CODE REVIEW

**Comment by littledan** [comment]
Is this necessary at this point? I thought we were good on the three-document version.

**Comment by leobalter** [comment]
@littledan Even if I prefer the split pages, this one is better for creating a final single document to send to Ecma.

The links on the top might also help with the navigation. 

Even though, we can keep some pages separated like the FAQ and References, but I don't believe this would help any much on the size.

**Comment by littledan** [comment]
If this is just about sending a document to ECMA, could it be a PDF which is the concatenation of each page, printed? I'm not sure we need to make the presentation to everyone be a single page just because of ECMA requirements, if it's better for normal users to have the multiple page version.

**Comment by leobalter** [comment]
At this point, I believe the navigation in the HTML version is not bad, and transforming it into PDF is simple and easy using this version. It also helps within editing and keeping things consistent in a single page.

I'd like to insist on this version, as I found that both modes are ok with minor pros and cons for each. Do you have any objection?

**Comment by leobalter** [comment]
One extra: this model allows navigation through GitHub if someone is reading the [index.md](https://github.com/tc39/code-of-conduct/blob/master/index.md) file directly.

**Comment by rwaldron** [comment]
> At this point, I believe the navigation in the HTML version is not bad, and transforming it into PDF is simple and easy using this version. It also helps within editing and keeping things consistent in a single page.

This is a compelling argument. 👍

**Pull request merged**
